// Function to fill PDF 
var pdfBuffer;
function fillPdf() {
  // Fill the PDF document with data

  try {
    var fields = {};
    var field_names = list_fields(pdfBuffer);
    var def1 = '';
    var def2 = false;
    var field_values = [
      [CHAmod], 
      [Acrobaties], 
      [Arcanes],
      [Athlétisme], 
      [Discrétion], 
      [Dressage], 
      [Escamotage], 
      [Histoire], 
      [Intuition], 
      [Investigation], 
      [Médecine], 
      [Nature], 
      [Perception], 
      [Représentation] 
      [Survie], 
      [Tromperie], 
      [Intimidation] ,
      [Persuasion] ,
      [Religion] ,
      [WISmod] ,
      [INTmod] ,
      [CONmod] ,
      [DEXmod] ,
      [STRmod] ,
      [Inspiration] ,
      [Maitrise] ,
      [STRsave] ,
      [DEXsave] ,
      [CONsave] ,
      [INTsave] ,
      [WISsave] ,
      [CHAsave] ,
      [CA] ,
      [Initiative] ,
      [Vitesse],
      [MaxHP] ,
      [HPActuel] ,
      [HPTmp] ,
      [Nom] ,
      [ClasseNiveau] ,
      [Historique] ,
      [NomJoueur] ,
      [Alignement] ,
      [Race] ,
      [EXP] ,
      [STR] ,
      [DEX] ,
      [CON] ,
      [INT] ,
      [WIS] ,
      [CHA] ,
      [Personnalite], 
      [Ideaux] ,
      [Liens] ,
      [Defauts] ,
      [TotalDeVie] ,
      [DeVieActuel] ,
      [JetMortEchec1] ,
      [JetMortEchec2] ,
      [JetMortEchec3] ,
      [Weapon1] ,
      [Weapon2] ,
      [Weapon3] ,
      [WeaponDmg1] ,
      [WeaponDmg2] ,
      [WeaponDmg3] ,
      [WeaponBonus1],
      [WeaponBonus2] ,
      [WeaponBonus3] ,
      [Incantations] ,
      [Capacite] ,
      [PerceptionPassive] ,
      [STRMaitrise] ,
      [DEXMaitrise] ,
      [CONMaitrise] ,
      [INTMaitrise] ,
      [WISMaitrise] ,
      [CHAMaitrise] ,
      [AcrobatieMaitrise] ,
      [ArcaneMaitrise] ,
      [AthletismeMaitrise] ,
      [DiscretionMaitrise] ,
      [DressageMaitrise] ,
      [EscamotageMaitrise] ,
      [HistoireMaitrise] ,
      [IntimidationMaitrise] ,
      [IntuitionMaitrise] ,
      [InvestigationMaitrise] ,
      [MedecineMaitrise] ,
      [NatureMaitrise] ,
      [PerceptionMaitrise] ,
      [PersuasionMaitrise] ,
      [ReligionMaitrise] ,
      [RepresentationMaitrise] ,
      [SurvieMaitrise] ,
      [TromperieMaitrise] ,
      [Copper] ,
      [Silver] ,
      [Electrum],
      [Gold] ,
      [Platinum] ,
      [Equipement] ,
      [MaitrisesLangues] ,
      [Nom2] ,
      [Age] ,
      [Taille] ,
      [Poids] ,
      [Yeux] ,
      [Peau] ,
      [Cheveux] ,
      [Apparence] ,
      [Allies] ,
      [NomAllies] ,
      [Background] ,
      [FeatTraits] ,
      [Tresor] ,
      [ClasseIncantation] ,
      [SortsAPreparer] ,
      [SpellSaveDC] ,
      [SpellAtkBonus] ,
      [Cantrips1] ,
      [Cantrips2] ,
      [Cantrips3] ,
      [Cantrips4] ,
      [Cantrips5] ,
      [Cantrips6] ,
      [Cantrips7] ,
      [Cantrips8] ,
      [SpellSlotLvl1] ,
      [SpellSlotLvl1Used] ,
      [def2],
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1],
      [def2] ,
      [def1] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [SpellLvl1_1] ,
      [SpellLvl1_2] ,
      [SpellLvl1_3] ,
      [SpellLvl1_4] ,
      [SpellLvl1_5] ,
      [SpellLvl1_6] ,
      [SpellLvl1_7] ,
      [SpellLvl1_8] ,
      [SpellLvl1_9] ,
      [SpellLvl1_10] ,
      [SpellLvl1_11] ,
      [SpellLvl1_12] ,
      [def1] ,
      [def1] ,
      [def2],
      [def2] ,
      [def2] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1],
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1],
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1], 
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def1], 
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def1] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2] ,
      [def1] ,
      [def2],
      ];

    for (var i = 0; i < field_names.length; i++) {
      console.log(field_names[i]);
      //fields[field_names[i]] = field_values[i];
    }
  } catch (e) {
    console.error('Error:', e);
  }

  /*try {
    filledPdfBuffer = pdfform(minipdf).transform(pdfBuffer, fields);
  } catch (e) {
    console.error('Error:', e);
  }

  // Download the filled PDF document
  var blob = new Blob([filledPdfBuffer], { type: 'application/pdf' });
  var link = document.createElement('a');
  link.href = window.URL.createObjectURL(blob);
  link.download = 'Filled_PDF_Document.pdf';
  link.click();*/
}

function list_fields(buf) {
  var field_names = [];
  try {
    var field_specs = pdfform().list_fields(buf);

    for (var field_key in field_specs) {
      field_names.push(field_key);
    }
    console.log('Fields:', field_names);
    return field_names;
  } catch (e) {
    on_error(e);
  }
}

// Attach click event listener to the button
document.addEventListener('DOMContentLoaded', function() {
  var url = './FeuillePersoDD5.pdf';

  var xhr = new XMLHttpRequest();
  xhr.open('GET', url, true);
  xhr.responseType = 'arraybuffer';

  xhr.onload = function() {
    if (this.status == 200) {
      pdfBuffer = this.response;
    } else {
      on_error('failed to load URL (code: ' + this.status + ')');
    }
  };
  xhr.send();

});

document.getElementById('fillPdfButton').addEventListener('click', fillPdf);
